# Generated by Django 6.1 on 2026-08-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_mgmt', '0002_strategyprofile_modelrun_strategy'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrun',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_runs', to='model_mgmt.strategyprofile'),
        ),
    ]
