"""
research/services/tier2_auditor.py
Nemotron 120B — Chief Risk Officer auditor (Tier 2 LLM).
"""
import json
import logging

from openai import OpenAI
from django.conf import settings

logger = logging.getLogger(__name__)

SYSTEM_INSTRUCTION = """
You are a Swing-Trading Risk Manager for the Indian Stock Market (NSE) specializing in short-term 15-day momentum breakouts.
Your task is to act as a final "event risk" filter for stocks that our Quantitative ML Engine has already identified as having momentum.

Core Directives for a 15-Day Hold:
1. TRUST THE ML MOMENTUM: If the ML Win Probability is high, the stock has active positive momentum. DO NOT reject stocks for "rich valuations", "high P/E", or being "overvalued". Momentum stocks are inherently expensive.
2. FUNDAMENTALS ARE A VETO, NOT A THESIS: Do not demand pristine long-term value. Only use fundamentals to catch catastrophic red flags (e.g., imminent bankruptcy, massive unserviceable debt). 
3. CATALYST FOCUS: Use the Tier 1 News Brief to confirm short-term momentum drivers (earnings beats, sector tailwinds) and veto catastrophic event risks (SEBI bans, fraud).

Hard Veto Rules (REJECT immediately ONLY if any are true):
1. Severe Insolvency: Debt-to-Equity > 3.0 (except Banks/NBFCs) AND actively burning cash.
2. Catastrophic Event Risk: Active SEBI investigations, proven fraud, or devastating overnight news.
3. Completely Broken Momentum: ML Win Probability < 45% AND overwhelmingly bearish news sentiment.

Decision Standard:
- APPROVE: If there is active momentum and NO imminent catastrophe (fraud, bankruptcy, or devastating news).
- REJECT: ONLY IF there is a severe event risk, extreme insolvency, or if the quantitative momentum is completely broken.

You MUST respond ONLY with a valid JSON object matching the requested schema. Do NOT wrap it in markdown blockquotes.
"""


def audit_stock(dossier: dict, news_brief: str) -> dict:
    """
    Tier 2: runs the Nemotron auditor and returns a parsed verdict dict.
    Raises on unrecoverable errors; returns error dict on JSON parse failure.
    """
    ticker = dossier["metadata"]["ticker"]
    prompt = f"""
Evaluate the following equity dossier and output your final audit verdict.

=== CANDIDATE DOSSIER ===
Ticker: {ticker}
LTP: ₹{dossier['quantitative_inputs']['ltp']}
ML Win Probability: {dossier['quantitative_inputs']['ml_win_probability'] * 100:.2f}%
Percentile Rank: Top {100 - dossier['quantitative_inputs']['percentile_rank']:.1f}%

--- FUNDAMENTALS & VALUATION ---
{json.dumps(dossier['fundamentals'], indent=2)}

--- TIER 1 NEWS BRIEF (DISTILLED FACTS) ---
{news_brief}

Output your evaluation strictly in the following JSON format:
{{
  "ticker": "{ticker}",
  "decision": "APPROVE" or "REJECT",
  "confidence_score": 0.00,
  "risk_flags": ["<string explaining flag, or empty if none>"],
  "fundamental_summary": "<brief assessment of debt, cashflow, and valuation>",
  "news_and_sentiment_summary": "<brief synthesis of the news brief>",
  "final_rationale": "<concise 2-sentence rationale for approval or rejection>",
  "recommended_allocation_inr": <number: 0 if REJECT, up to 20000 if APPROVE>
}}
"""
    try:
        logger.info("  [Tier 2] Auditing %s...", ticker)
        client = OpenAI(base_url=settings.NIM_BASE_URL, api_key=settings.NVIDIA_API_KEY)
        response = client.chat.completions.create(
            model=settings.NVIDIA_REASONING_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_INSTRUCTION},
                {"role": "user", "content": prompt}
            ],
            temperature=0.0,
            max_tokens=8000,
        )
        content = response.choices[0].message.content
        if not content:
            raise ValueError("No response generated by Tier 2 LLM.")
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:]
        elif content.startswith("```"):
            content = content[3:]
        
        content = content.strip()
        if content.endswith("```"):
            content = content[:-3].strip()
        
        return json.loads(content)
    except Exception as exc:
        logger.error("Tier 2 auditor failed for %s: %s", ticker, exc)
        return {
            "ticker": ticker,
            "decision": "REJECT",
            "confidence_score": 0.0,
            "risk_flags": [f"LLM Parsing Error: {exc}"],
            "fundamental_summary": "",
            "news_and_sentiment_summary": "",
            "final_rationale": "Audit failed due to error.",
            "recommended_allocation_inr": 0,
        }
