import json
import logging

from openai import OpenAI, AzureOpenAI
from django.conf import settings

logger = logging.getLogger(__name__)

SYSTEM_INSTRUCTION = """
You are a ruthless, aggressively critical Swing-Trading Risk Manager for the Indian Stock Market (NSE).
Your task is to act as the ultimate "Red Flag Hunter" for short-term 15-day momentum trades. The Quantitative ML Engine has already passed these stocks to you, but ML models are blind to context, earnings traps, and sudden macro shifts. You are the final line of defense to protect capital.

Core Directives for a 15-Day Hold:
1. HUNT FOR RED FLAGS: Actively search the news and fundamentals for any reason a stock might drop in the next 15 days. Look for insider selling, poor earnings guidance, sector headwinds, regulatory crackdowns, or sudden management changes.
2. VALUATION AND DEBT MATTER: While momentum stocks can run hot, extreme overvaluation combined with high debt is a ticking time bomb. Be highly skeptical of companies with negative operating cash flow or Debt-to-Equity > 1.5.
3. PRESERVE CAPITAL: It is ALWAYS better to reject a mediocre setup than to risk capital. Be ruthless. If the news is just "okay" but not great, REJECT. If there is no clear upcoming catalyst, REJECT. 
4. SYNTHESIZE BROAD CONTEXT: You will be provided with a broad executive summary of the current news and qualitative realities. You must weigh this nuanced reality heavily against the strict numerical fundamentals.

Hard Veto Rules (REJECT immediately if ANY are true):
1. Weak Fundamentals: High debt, burning cash, or consistently declining profit margins.
2. Macro/Sector Headwinds: Negative news affecting the broader sector or regulatory environment.
3. Catalyst Vacuum: No clear positive momentum drivers or earnings beats in the recent news.
4. Any mention of SEBI probes, auditor resignations, or promoter pledging.

Decision Standard:
- REJECT: This should be your default stance. Reject if there is ANY ambiguity, weakness in fundamentals, negative qualitative reality, or lack of a strong positive catalyst.
- APPROVE: ONLY if the stock has pristine short-term catalysts, clean fundamentals, and absolute zero event risk.

You MUST respond ONLY with a valid JSON object matching the requested schema. Do NOT wrap it in markdown blockquotes.
"""


def audit_stock(dossier: dict, news_brief: str) -> dict:
    ticker = dossier["metadata"]["ticker"]
    prompt = f"""
Evaluate the following equity dossier and output your final audit verdict.

=== CANDIDATE DOSSIER ===
Ticker: {ticker}
LTP: ₹{dossier['quantitative_inputs']['ltp']}
ML Win Probability: {dossier['quantitative_inputs']['ml_win_probability'] * 100:.2f}%
Percentile Rank: Top {100 - dossier['quantitative_inputs']['percentile_rank']:.1f}%

--- FUNDAMENTALS & VALUATION ---
{json.dumps(dossier['fundamentals'], indent=2)}

--- TIER 1 NEWS BRIEF (BROAD CONTEXT) ---
{news_brief}

You MUST output ONLY a valid JSON object with the following exact keys and no other text:
{{
    "decision": "APPROVE" or "REJECT",
    "confidence_score": <float between 0.0 and 1.0>,
    "risk_flags": [<list of strings detailing major risks, missing data, or bad qualitative signals>],
    "fundamental_summary": "<brief summary of valuation and cash flow>",
    "news_context_summary": "<brief summary of Tier 1 news context>",
    "final_rationale": "<1 paragraph explaining the decision>",
    "recommended_allocation_inr": <int: 0 if REJECT, up to 20000 if APPROVE>
}}
"""
    try:
        logger.info("  [Tier 2] Auditing %s...", ticker)
        
        if settings.LLM_PROVIDER == "azure":
            client = AzureOpenAI(
                api_key=settings.AZURE_OPENAI_KEY,
                api_version=settings.AZURE_OPENAI_API_VERSION,
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                max_retries=3
            )
            target_model = settings.AZURE_OPENAI_REASONING_DEPLOYMENT_NAME
        else:
            client = OpenAI(
                base_url=settings.NIM_BASE_URL, 
                api_key=settings.NVIDIA_API_KEY,
                max_retries=3
            )
            target_model = settings.NVIDIA_REASONING_MODEL

        response = client.chat.completions.create(
            model=target_model,
            messages=[
                {"role": "system", "content": SYSTEM_INSTRUCTION},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=8000,
        )
        content = response.choices[0].message.content
        if not content:
            raise ValueError("No response generated by Tier 2 LLM.")
        content = content.strip()
        if content.startswith("`json"):
            content = content[7:]
        elif content.startswith("`"):
            content = content[3:]
        
        content = content.strip()
        if content.endswith("`"):
            content = content[:-3].strip()
        
        return json.loads(content)
    except Exception as exc:
        logger.error("Tier 2 auditor failed for %s: %s", ticker, exc)
        return {
            "ticker": ticker,
            "decision": "REJECT",
            "confidence_score": 0.0,
            "risk_flags": [f"LLM Parsing Error: {exc}"],
            "fundamental_summary": "",
            "news_and_sentiment_summary": "",
            "final_rationale": "Audit failed due to error.",
            "recommended_allocation_inr": 0,
        }
