import json
import logging

from openai import OpenAI, AzureOpenAI
from django.conf import settings

logger = logging.getLogger(__name__)

SYSTEM_INSTRUCTION = """
You are an objective, balanced Swing-Trading Risk Manager for the Indian Stock Market (NSE).
Your task is to act as a sensible final check for short-term 15-day momentum trades. The Quantitative ML Engine has already identified strong technical momentum for these stocks, and a Pre-ML Screener has already confirmed their basic fundamentals (positive cash flow, reasonable debt). Your job is to read the news context and catch major event risks the math cannot see.

Core Directives for a 15-Day Hold:
1. IDENTIFY REAL RED FLAGS: Look for confirmed, active threats like SEBI investigations, auditor resignations, sudden massive earnings misses, or fraud allegations.
2. ALLOW NEUTRAL-TO-POSITIVE NEWS: Since the ML model has already confirmed the stock is breaking out technically, the news does NOT need to be explosive. If the news is generally neutral, business-as-usual, or mildly positive, APPROVE the stock. 
3. DON'T OVER-ANALYZE VALUATION: Momentum stocks often look overvalued. As long as there is no active threat or massive fundamental deterioration, trust the ML model's momentum score.
4. SYNTHESIZE BROAD CONTEXT: Weigh the news context reasonably. Do not reject a stock just because it lacks a massive upcoming catalyst. 

Hard Veto Rules (REJECT ONLY if ANY are true):
1. Confirmed Fraud/Regulatory Action: Any mention of SEBI probes, auditor resignations, or promoter pledging defaults.
2. Severe Macro/Sector Headwinds: Widespread, severe negative news actively destroying the sector right now.
3. Sudden Fundamental Collapse: News of a massive unexpected earnings miss or bankruptcy risk.

Decision Standard:
- APPROVE: This should be your stance for the majority of these pre-screened stocks. Approve if the news is neutral or positive, and there are no severe active red flags.
- REJECT: ONLY reject if you find a specific, confirmed landmine (fraud, severe earnings shock, active regulatory action) that makes a 15-day hold highly dangerous.

You MUST respond ONLY with a valid JSON object matching the requested schema. Do NOT wrap it in markdown blockquotes.
"""


def audit_stock(dossier: dict, news_brief: str) -> dict:
    ticker = dossier["metadata"]["ticker"]
    prompt = f"""
Evaluate the following equity dossier and output your final audit verdict.

=== CANDIDATE DOSSIER ===
Ticker: {ticker}
LTP: ₹{dossier['quantitative_inputs']['ltp']}
ML Win Probability: {dossier['quantitative_inputs']['ml_win_probability'] * 100:.2f}%
Percentile Rank: Top {100 - dossier['quantitative_inputs']['percentile_rank']:.1f}%

--- FUNDAMENTALS & VALUATION ---
{json.dumps(dossier['fundamentals'], indent=2)}

--- TIER 1 NEWS BRIEF (BROAD CONTEXT) ---
{news_brief}

You MUST output ONLY a valid JSON object with the following exact keys and no other text:
{{
    "decision": "APPROVE" or "REJECT",
    "confidence_score": <float between 0.0 and 1.0>,
    "risk_flags": [<list of strings detailing major risks, missing data, or bad qualitative signals>],
    "fundamental_summary": "<brief summary of valuation and cash flow>",
    "news_context_summary": "<brief summary of Tier 1 news context>",
    "final_rationale": "<1 paragraph explaining the decision>",
    "recommended_allocation_inr": <int: 0 if REJECT, up to 20000 if APPROVE>
}}
"""
    try:
        logger.info("  [Tier 2] Auditing %s...", ticker)
        
        if settings.LLM_PROVIDER == "azure":
            client = AzureOpenAI(
                api_key=settings.AZURE_OPENAI_KEY,
                api_version=settings.AZURE_OPENAI_API_VERSION,
                azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                max_retries=3
            )
            target_model = settings.AZURE_OPENAI_REASONING_DEPLOYMENT_NAME
        else:
            client = OpenAI(
                base_url=settings.NIM_BASE_URL, 
                api_key=settings.NVIDIA_API_KEY,
                max_retries=3
            )
            target_model = settings.NVIDIA_REASONING_MODEL

        response = client.chat.completions.create(
            model=target_model,
            messages=[
                {"role": "system", "content": SYSTEM_INSTRUCTION},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=8000,
        )
        content = response.choices[0].message.content
        if not content:
            raise ValueError("No response generated by Tier 2 LLM.")
        content = content.strip()
        if content.startswith("`json"):
            content = content[7:]
        elif content.startswith("`"):
            content = content[3:]
        
        content = content.strip()
        if content.endswith("`"):
            content = content[:-3].strip()
        
        return json.loads(content)
    except Exception as exc:
        logger.error("Tier 2 auditor failed for %s: %s", ticker, exc)
        return {
            "ticker": ticker,
            "decision": "REJECT",
            "confidence_score": 0.0,
            "risk_flags": [f"LLM Parsing Error: {exc}"],
            "fundamental_summary": "",
            "news_and_sentiment_summary": "",
            "final_rationale": "Audit failed due to error.",
            "recommended_allocation_inr": 0,
        }
