# Generated by Django 6.1 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('log_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to='signals.signalrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('tier1_news_brief', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_flags', models.JSONField(default=list)),
                ('fundamental_summary', models.TextField(blank=True)),
                ('news_sentiment_summary', models.TextField(blank=True)),
                ('final_rationale', models.TextField(blank=True)),
                ('recommended_allocation_inr', models.FloatField(default=0.0)),
                ('fundamentals_json', models.JSONField(default=dict)),
                ('raw_verdict_json', models.JSONField(default=dict)),
                ('ltp', models.FloatField(default=0.0)),
                ('win_probability', models.FloatField(default=0.0)),
                ('percentile_rank', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='research.researchrun')),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
    ]
