# Generated by Django 6.1 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('log_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_runs', to='research.researchrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('dhan_security_id', models.CharField(blank=True, max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('allocated_inr', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(default='BUY', max_length=4)),
                ('dhan_order_id', models.CharField(blank=True, max_length=100)),
                ('dhan_status', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSIT', 'Transit'), ('TRADED', 'Traded'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('dhan_raw_response', models.JSONField(default=dict)),
                ('fee_zerodha', models.FloatField(default=0.0)),
                ('fee_dhan', models.FloatField(default=0.0)),
                ('fee_groww', models.FloatField(default=0.0)),
                ('fee_angel', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='research.stockdecision')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='execution.executionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
