# Generated by Django 6.1 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPnL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('unrealized_pnl', models.FloatField(default=0.0)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('total_positions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('entry_price', models.FloatField()),
                ('current_price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('tp_price', models.FloatField()),
                ('sl_price', models.FloatField()),
                ('max_hold_days', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('unrealized_pnl', models.FloatField(default=0.0)),
                ('unrealized_pnl_pct', models.FloatField(default=0.0)),
                ('days_held', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='execution.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_price', models.FloatField()),
                ('exit_date', models.DateField()),
                ('exit_reason', models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('EXPIRY', 'Time Expiry'), ('MANUAL', 'Manual Close')], max_length=10)),
                ('gross_pnl', models.FloatField()),
                ('net_pnl_zerodha', models.FloatField(default=0.0)),
                ('net_pnl_dhan', models.FloatField(default=0.0)),
                ('net_pnl_groww', models.FloatField(default=0.0)),
                ('net_pnl_angel', models.FloatField(default=0.0)),
                ('total_fee_zerodha', models.FloatField(default=0.0)),
                ('total_fee_dhan', models.FloatField(default=0.0)),
                ('total_fee_groww', models.FloatField(default=0.0)),
                ('total_fee_angel', models.FloatField(default=0.0)),
                ('hold_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='portfolio.position')),
            ],
            options={
                'ordering': ['-exit_date'],
            },
        ),
    ]
