# Generated by Django 6.1 on 2026-08-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_mgmt', '0002_strategyprofile_modelrun_strategy'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ai_decision',
            field=models.CharField(default='APPROVE', max_length=10),
        ),
        migrations.AddField(
            model_name='position',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='model_mgmt.strategyprofile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='ai_decision',
            field=models.CharField(default='APPROVE', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='model_mgmt.strategyprofile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_reason',
            field=models.CharField(choices=[('TP', 'Take Profit'), ('EXPIRY', 'Time Expiry'), ('MANUAL', 'Manual Close'), ('SL', 'Stop Loss')], max_length=10),
        ),
    ]
