# Generated by Django 6.1 on 2026-08-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_position_ai_decision_position_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_high_15d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='max_low_15d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='threshold_hit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='threshold_hit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='threshold_hit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
