# Generated by Django 6.1 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('fold1_base_rate', models.FloatField(blank=True, null=True)),
                ('fold1_precision', models.FloatField(blank=True, null=True)),
                ('fold2_base_rate', models.FloatField(blank=True, null=True)),
                ('fold2_precision', models.FloatField(blank=True, null=True)),
                ('fold3_base_rate', models.FloatField(blank=True, null=True)),
                ('fold3_precision', models.FloatField(blank=True, null=True)),
                ('total_samples', models.IntegerField(blank=True, null=True)),
                ('total_stocks', models.IntegerField(blank=True, null=True)),
                ('feature_importances', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_line', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='model_mgmt.modelrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
