# Generated by Django 6.1 on 2026-08-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tp_target', models.FloatField(default=0.03)),
                ('sl_stop', models.FloatField(default=-0.02)),
                ('hold_days', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelrun',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='model_mgmt.strategyprofile'),
        ),
    ]
