# Generated by Django 6.1 on 2026-08-27 07:55

from django.db import migrations


def create_default_strategy_and_link(apps, schema_editor):
    StrategyProfile = apps.get_model('model_mgmt', 'StrategyProfile')
    ModelRun = apps.get_model('model_mgmt', 'ModelRun')
    SignalRun = apps.get_model('signals', 'SignalRun')
    Position = apps.get_model('portfolio', 'Position')
    Trade = apps.get_model('portfolio', 'Trade')
    
    # Create legacy strategy
    legacy, _ = StrategyProfile.objects.get_or_create(
        name="Legacy 3/2",
        defaults={
            "tp_target": 0.03,
            "sl_stop": -0.02,
            "hold_days": 15,
            "is_active": True
        }
    )
    
    # Update existing runs
    ModelRun.objects.filter(strategy__isnull=True).update(strategy=legacy)
    SignalRun.objects.filter(strategy__isnull=True).update(strategy=legacy)
    Position.objects.filter(strategy__isnull=True).update(strategy=legacy, ai_decision="APPROVE")
    Trade.objects.filter(strategy__isnull=True).update(strategy=legacy, ai_decision="APPROVE")

class Migration(migrations.Migration):

    dependencies = [
        ('model_mgmt', '0002_strategyprofile_modelrun_strategy'),
        ('portfolio', '0002_position_ai_decision_position_strategy_and_more'),
        ('signals', '0002_signalrun_strategy'),
    ]

    operations = [
        migrations.RunPython(create_default_strategy_and_link, reverse_code=migrations.RunPython.noop),
    ]
